# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Automatika

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.HOST_IP }}
                  username: ${{ vars.HOST_USERNAME }}
                  key: ${{ secrets.HOST_SSH_KEY }}
                  port: ${{ vars.HOST_PORT }}
                  script: |
                      cd /home/ubuntu/git/Main
                      git pull
                      export NVM_DIR=~/.nvm
                      source ~/.nvm/nvm.sh
                      pnpm install -P
                      pm2 del ampix-main
                      pnpm run build
                      pm2 start main.config.cjs
